spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ecomdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  application:
    name: ecom-platform
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
